# Generated by Django 5.2 on 2025-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='is_iranian',
        ),
        migrations.AddField(
            model_name='dish',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
