# Generated by Django 5.2 on 2025-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
