# Generated by Django 5.2 on 2025-04-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('menu', '0004_dish_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.image'),
        ),
    ]
