# Generated by Django 5.2 on 2025-04-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
