# Generated by Django 5.2 on 2025-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_likedish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
