# Generated by Django 5.2 on 2025-04-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_dishimage_delete_image'),
        ('menu', '0009_likedish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish'),
        ),
    ]
