# Generated by Django 5.2 on 2025-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_dishimage_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(upload_to='dish_images/'),
        ),
    ]
