# Generated by Django 5.2 on 2025-04-18 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_branch'),
        ('media', '0004_alter_dishimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishimage',
            name='name',
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branch_images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inbox.branch')),
            ],
        ),
    ]
