# Generated by Django 5.2 on 2025-04-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_branch'),
        ('media', '0005_remove_dishimage_name_branchimage'),
        ('menu', '0010_dish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchimage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inbox.branch'),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_images/'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
